import { v4 as uuidv4 } from "uuid";

export const Rooms = [
  {
    id: uuidv4(),
    description: "Chnambre du luxe 1",
    size: "250",
    guests: "4",
    roomType: "family room",
    pets: false,
    picture: "pictures/pic.jfif",
    price: 1000,
    Breakfast: true,
  },
  {
    id: uuidv4(),
    description: "chambre du lux2",
    picture: "pictures/pic2.jfif",
    price: 2000,
    size: "300",
    guests: "4",
    roomType: "single room",
    pets: true,
    Breakfast: true,
  },
  {
    id: uuidv4(),
    description: "chambre du luxe 3",
    picture: "pictures/pic2.jfif",
    price: 2500,
    size: "350",
    guests: "2",
    roomType: "family room",
    pets: true,
    Breakfast: true,
  },
  {
    id: uuidv4(),
    description: "chambre du luxe 4",
    picture: "pictures/pic3.jfif",
    price: 3000,
    size: "400",
    guests: "3",
    roomType: "luxiourious family room",
    pets: true,
    Breakfast: false,
  },
  {
    id: uuidv4(),
    description: "chambre du luxe 5",
    picture: "pictures/pic4.jfif",
    price: 3000,
    size: "250",
    guests: "2",
    roomType: "family room",
    breakfast: true,
    pets: true,
  },
  {
    id: uuidv4(),
    description: "chambre du luxe 4",
    picture: "pictures/pic3.jfif",
    price: 2000,
    size: "300",
    guests: "4",
    roomType: "single room",
    breakfast: false,
    pets: false,
  },
  {
    id: uuidv4(),
    description: "chambre du luxe 5",
    picture: "pictures/pic4.jfif",
    price: 6000,
    size: "250",
    guests: "2",
    roomType: "family room",
    breakfast: true,
    pets: false,
  },
  {
    id: uuidv4(),
    description: "chambre du luxe 4",
    picture: "pictures/pic3.jfif",
    price: 6000,
    size: "250",
    guests: "2",
    roomType: "family room",
    pets: true,
    breakfast: false,
  },
  {
    id: uuidv4(),
    description: "chambre du luxe 5",
    picture: "pictures/pic4.jfif",
    price: 6000,
    size: "250",
    guests: "2",
    roomType: "family room",
    pets: true,
    breakfast: true,
  },
  {
    id: uuidv4(),
    description: "chambre du luxe 4",
    picture: "pictures/pic3.jfif",
    price: 3000,
    size: "250",
    guests: "2",
    roomType: "family room",
    pets: false,
    breakfast: false,
  },
  {
    id: uuidv4(),
    description: "chambre du luxe 5",
    picture: "pictures/pic4.jfif",
    price: 6000,
    size: "250",
    guests: "2",
    roomType: "family room",
    pets: true,
    breakfast: true,
  },
];
